
version: '3.7'

services:
  app:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - "DB_HOST=db"
      - "DB_NAME=mydb"
      - "DB_USERNAME=myuser"
      - "DB_PASSWORD=mypassword"
      - "DB_PORT=5432"
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=mydb"
      - "POSTGRES_USER=myuser"
      - "POSTGRES_PASSWORD=mypassword"
    ports:
      - '5432:5432'
volumes:
  postgres_db:
