# Generated by Django 3.1.7 on 2021-04-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210420_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='links',
            new_name='link',
        ),
    ]
